export {default as AccountLogin} from './LoginAndRegister/Login'
export {default as SiteHeader} from './header'
export {default as Posts} from './posts/posts'
export {default as Register} from './LoginAndRegister/register'
export {default as SinglePost} from './singlePost/singlePost'
export {default as NewPost} from './NewPost/NewPost'
export {default as Account} from './AccountInfo/accountInfo'